FROM jenkins/jenkins:lts
COPY configs/jenkins/plugins.txt /usr/share/jenkins/ref/plugins.txt
COPY configs/jenkins/jenkins.yaml $JENKINS_HOME/jenkins.yaml
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
